bag_dir: /home/ubuntu-2004/SLAM_datasets/EuRoC/MH_03/MH_03_medium.bag
img_topic: /cam0/image_raw

threshold: 0.3

# Camera specific definitions.
rate_hz: 20
resolution: [752, 480]
camera_model: pinhole
intrinsics: [458.654, 457.296, 367.215, 248.375] #fu, fv, cu, cv
distortion_model: radial-tangential
distortion_coefficients: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]